//! Safe Rust wrapper around the DECtalk text-to-speech C library.
//!
//! DECtalk is a classic TTS engine from the 80s/90s, famous for its robotic
//! voice. This module provides a minimal safe API over the raw C bindings
//! generated by `bindgen` at build time (see `build.rs`).
//!
//! # Safety model
//!
//! All `unsafe` blocks are confined to this module. Each call to a C function
//! is wrapped by [`check_mm`], which converts the Windows `MMRESULT` error
//! code into a typed [`DectalkError::Mm`]. The [`Dectalk`] struct owns the
//! opaque handle and shuts the library down via [`Drop`].
//!
//! # Usage
//!
//! ```ignore
//! let tts = Dectalk::new()?;
//! tts.speak_to_wav("Hello world", "/tmp/out.wav", WaveFormat::DT_1M16)?;
//! ```

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
use crate::pawthos::types::Result;
use std::{
    ffi::{CString, NulError, c_void},
    path::Path,
    ptr::{self, NonNull},
};
// Generated in build.rs as OUT_DIR/dectalk_bindings.rs
include!(concat!(env!("OUT_DIR"), "/dectalk_bindings.rs"));

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors that can occur when initialising or using DECtalk.
#[derive(Debug)]
pub enum DectalkError {
    /// A DECtalk C function returned a non-zero `MMRESULT` error code.
    ///
    /// `loc` captures the call site via `#[track_caller]` so log messages
    /// include the Rust source location of the failing call.
    Mm {
        error_code: MMRESULT,
        loc: std::panic::Location<'static>,
    },

    /// `TextToSpeechStartup` returned a null handle despite reporting success.
    ///
    /// Should never happen in practice; indicates a serious library issue.
    NullHandle,

    /// A string passed to DECtalk contained an interior NUL byte.
    ///
    /// DECtalk expects C strings; [`CString::new`] rejects strings with
    /// embedded NULs and returns a [`NulError`].
    FfiNul(std::ffi::NulError),
}

impl std::fmt::Display for DectalkError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DectalkError::Mm { error_code, loc } => {
                write!(f, "DectalkMmError {} at {}", error_code, loc)
            }
            DectalkError::NullHandle => write!(f, "DectalkNullHandleError"),
            DectalkError::FfiNul(e) => write!(f, "Nul byte found in string: {}", e),
        }
    }
}

impl From<NulError> for DectalkError {
    fn from(e: NulError) -> Self {
        DectalkError::FfiNul(e)
    }
}

impl std::error::Error for DectalkError {}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Check a `MMRESULT` return code and convert non-zero values into an error.
///
/// `#[track_caller]` causes the `Location` stored in the error to point at
/// the call site (inside [`Dectalk`] methods) rather than here.
#[track_caller]
fn check_mm(code: MMRESULT) -> Result<(), DectalkError> {
    if code == 0 {
        Ok(())
    } else {
        let loc = std::panic::Location::caller();

        let e = DectalkError::Mm {
            error_code: (code),
            loc: (*loc),
        };
        Err(e)
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// A live DECtalk TTS engine instance.
///
/// Wraps the opaque `LPTTS_HANDLE_T` pointer returned by
/// `TextToSpeechStartup`. The handle is shut down when the struct is dropped.
///
/// # Thread safety
///
/// DECtalk is not thread-safe; use one `Dectalk` per thread. The [`crate::commands::vox`]
/// command creates a fresh instance inside `spawn_blocking` for every invocation.
#[derive(Debug)]
pub struct Dectalk {
    handle: NonNull<c_void>,
}

/// Output audio format options for [`Dectalk::speak_to_wav`].
pub enum WaveFormat {
    // Mono 8-bit, 11.025 kHz sample rate
    //    DT_1M08 = 1,

    /// Mono 16-bit, 11.025 kHz sample rate.
    ///
    /// This is the format used by the `/vox say` command. It produces good
    /// quality at a small file size.
    DT_1M16 = 4,
    // Mono 8-bit, m-law 8 kHz sample rate
    //   DT_08M08 = 0x1000,
}

impl Dectalk {
    /// Initialise the DECtalk library and return a handle.
    ///
    /// Uses no window/callback and default device options. Output is directed
    /// to a WAV file via [`speak_to_wav`]; there is no real-time audio output.
    ///
    /// # Errors
    /// Returns [`DectalkError::Mm`] if `TextToSpeechStartup` fails, or
    /// [`DectalkError::NullHandle`] if it returns a null pointer despite
    /// reporting success.
    ///
    /// [`speak_to_wav`]: Dectalk::speak_to_wav
    pub fn new() -> Result<Self, DectalkError> {
        log::debug!("Dectalk::new()");
        let mut raw: LPTTS_HANDLE_T = ptr::null_mut();
        // SAFETY: TextToSpeechStartup is safe because we know that LPTTS_HANDLE_T is a proper null_mut pointer
        // before the function call, and we check if the handle is null afterwards.
        // for more information on the TextToSpeechStarup, visit https://dectalk.github.io/dectalk/dectalk.htm
        let rc = unsafe { TextToSpeechStartup(&mut raw, 0, 0, None, 0) };
        check_mm(rc)?;

        let handle = NonNull::new(raw).ok_or(DectalkError::NullHandle)?;
        Ok(Self { handle })
    }

    /// Synthesise `text` as speech and write it to `out_path` as a WAV file.
    ///
    /// The call blocks until DECtalk has finished synthesising all queued
    /// speech (`TextToSpeechSync`). Interior NUL bytes are stripped from
    /// `text` before it is passed to the C library.
    ///
    /// # Parameters
    /// - `text`     — the text to synthesise (DECtalk markup is supported).
    /// - `out_path` — destination file path; created or overwritten.
    /// - `format`   — audio format (use [`WaveFormat::DT_1M16`] for Discord).
    ///
    /// # Errors
    /// Returns a [`DectalkError`] if any underlying C call fails.
    pub fn speak_to_wav(
        &self,
        text: &str,
        out_path: impl AsRef<Path>,
        format: WaveFormat,
    ) -> Result<(), DectalkError> {
        // Open the wave file output
        let cpath = CString::new(out_path.as_ref().to_string_lossy().as_bytes())?;
        check_mm(unsafe {
            TextToSpeechOpenWaveOutFile(
                self.handle.as_ptr(),
                cpath.as_ptr() as *mut i8,
                format as DWORD,
            )
        })?;

        // Speak the text in normal mode (ASCII expected by this entry point)
        let mut bytes = text.as_bytes().to_vec();
        bytes.retain(|&b| b != 0); // strip interior NULs
        let ctext = CString::new(bytes)?;
        check_mm(unsafe {
            TextToSpeechSpeak(self.handle.as_ptr(), ctext.as_ptr() as *mut i8, TTS_NORMAL)
        })?;

        // Wait until all queued speech is done
        check_mm(unsafe { TextToSpeechSync(self.handle.as_ptr()) })?;

        // Close the wave file
        check_mm(unsafe { TextToSpeechCloseWaveOutFile(self.handle.as_ptr()) })?;
        Ok(())
    }
}

/// Shut down the DECtalk engine and release its resources.
impl Drop for Dectalk {
    fn drop(&mut self) {
        unsafe {
            let _ = TextToSpeechShutdown(self.handle.as_ptr());
        }
    }
}
