//! Compile-time constants shared across the bot.
//!
//! All magic numbers and strings live here so they are easy to find and
//! change in one place. Import what you need with
//! `use crate::pawthos::consts::*;` or pick individual names.

use poise::serenity_prelude as serenity;
use serenity::Color;
use serenity::GatewayIntents;

/// The set of Discord Gateway intents the bot requires.
///
/// - `GUILD_MESSAGES` — receive messages sent in guild channels.
/// - `DIRECT_MESSAGES` — receive messages sent in DMs (used for schedule reminders).
/// - `MESSAGE_CONTENT` — receive the actual text of messages (required for mimic auto-mode).
/// - `GUILD_MESSAGE_REACTIONS` — receive reaction-add events (required for the
///   tab-reaction faucet in [`crate::handlers`]).
pub const INTENTS: GatewayIntents = {
    let mut r = GatewayIntents::GUILD_MESSAGES;
    r = GatewayIntents::union(r, GatewayIntents::DIRECT_MESSAGES);
    r = GatewayIntents::union(r, GatewayIntents::MESSAGE_CONTENT);
    r = GatewayIntents::union(r, GatewayIntents::GUILD_MESSAGE_REACTIONS);
    r
};

/// The bot's "success" embed accent colour — a soft green.
pub const LOGOS_GREEN: Color = Color::from_rgb(102, 204, 102);

/// The bot's "error" embed accent colour — a bright red.
pub const LOGOS_RED: Color = Color::from_rgb(255, 0, 0);

/// Discord user ID of the bot owner (Fizzy).
///
/// Several admin-only prefix commands gate on this ID to prevent abuse.
pub const FIZZ_ID: serenity::UserId = serenity::UserId::new(326389428593623040);

/// Number of tabs awarded by the `/daily` command.
pub const DAILY_REWARD: i64 = 10;

/// Cost in tabs to set or change a custom colour role via `/color set`.
pub const COLOR_ROLE_COST: i64 = 10;

/// The Discord custom-emoji string for the "tab" currency emoji.
///
/// Used wherever the tab balance is displayed to users.
pub const TAB_EMOJI: &str = "<:tab:1459045305084547123>";

/// Numeric emoji ID matching [`TAB_EMOJI`]. Used to construct a
/// [`poise::serenity_prelude::ReactionType`] for the faucet.
pub const TAB_EMOJI_ID: u64 = 1459045305084547123;

/// Short emoji name matching [`TAB_EMOJI`]. Required when building a
/// `ReactionType::Custom` — Discord accepts the ID alone but serenity's
/// emoji helpers prefer having the name populated.
pub const TAB_EMOJI_NAME: &str = "tab";

/// Side length in pixels of the PNG preview generated by `/color preview`.
pub const COLOR_PREVIEW_SIZE: u32 = 256;

/// Maximum bonus tabs from a daily streak.
///
/// At streak day 1 the user gets `DAILY_REWARD`. Each consecutive day adds +1
/// tab up to this cap. So the max daily payout is `DAILY_REWARD + MAX_STREAK_BONUS`.
pub const MAX_STREAK_BONUS: i64 = 5;

/// Number of entries shown on the `/leaderboard` embed.
pub const LEADERBOARD_SIZE: usize = 10;

// ---------------------------------------------------------------------------
// Shop / inventory
// ---------------------------------------------------------------------------

/// Extra tabs paid by the sender on top of an item's price when gifting.
pub const GIFT_FEE: i64 = 2;

/// Maximum number of badges a user may pin to their profile at once.
pub const MAX_ACTIVE_BADGES: usize = 3;

/// Maximum character length for a user-supplied custom title.
pub const MAX_CUSTOM_TITLE_LEN: usize = 32;

// ---------------------------------------------------------------------------
// Tab reaction faucet (Phase 5)
// ---------------------------------------------------------------------------

/// Probability that any given guild message spawns a faucet bounty.
///
/// Combined with [`FAUCET_GLOBAL_COOLDOWN_SECS`] to bound total bounty rate.
pub const FAUCET_TRIGGER_CHANCE: f64 = 0.005;

/// Tabs awarded to the first user to click the bot's tab reaction.
pub const FAUCET_REWARD: i64 = 5;

/// Seconds a bounty stays live before the bot removes its reaction.
pub const FAUCET_EXPIRY_SECS: i64 = 600;

/// Minimum seconds between consecutive bounty spawns, regardless of
/// [`FAUCET_TRIGGER_CHANCE`] rolls.
pub const FAUCET_GLOBAL_COOLDOWN_SECS: i64 = 120;

// ---------------------------------------------------------------------------
// Lootbox tuning (Phase 8)
// ---------------------------------------------------------------------------

/// Cost per lootbox pull.
pub const LOOTBOX_COST: i64 = 15;

/// Tabs refunded when a pull would have granted a duplicate badge.
pub const LOOTBOX_SALVAGE: i64 = 3;

pub const LOOTBOX_CHANCE_COMMON: f64 = 0.60;
pub const LOOTBOX_CHANCE_UNCOMMON: f64 = 0.25;
pub const LOOTBOX_CHANCE_RARE: f64 = 0.10;
pub const LOOTBOX_CHANCE_LEGENDARY: f64 = 0.05;
