//! Compile-time constants shared across the bot.
//!
//! All magic numbers and strings live here so they are easy to find and
//! change in one place. Import what you need with
//! `use crate::pawthos::consts::*;` or pick individual names.

use poise::serenity_prelude as serenity;
use serenity::Color;
use serenity::GatewayIntents;

/// The set of Discord Gateway intents the bot requires.
///
/// - `GUILD_MESSAGES` — receive messages sent in guild channels.
/// - `DIRECT_MESSAGES` — receive messages sent in DMs (used for schedule reminders).
/// - `MESSAGE_CONTENT` — receive the actual text of messages (required for mimic auto-mode).
pub const INTENTS: GatewayIntents = {
    let mut r = GatewayIntents::GUILD_MESSAGES;
    r = GatewayIntents::union(r, GatewayIntents::DIRECT_MESSAGES);
    r = GatewayIntents::union(r, GatewayIntents::MESSAGE_CONTENT);
    r
};

/// The bot's "success" embed accent colour — a soft green.
pub const LOGOS_GREEN: Color = Color::from_rgb(102, 204, 102);

/// The bot's "error" embed accent colour — a bright red.
pub const LOGOS_RED: Color = Color::from_rgb(255, 0, 0);

/// Discord user ID of the bot owner (Fizzy).
///
/// Several admin-only prefix commands gate on this ID to prevent abuse.
pub const FIZZ_ID: serenity::UserId = serenity::UserId::new(326389428593623040);

/// Number of tabs awarded by the `/daily` command.
pub const DAILY_REWARD: i64 = 10;

/// Cost in tabs to set or change a custom colour role via `/color set`.
pub const COLOR_ROLE_COST: i64 = 10;

/// The Discord custom-emoji string for the "tab" currency emoji.
///
/// Used wherever the tab balance is displayed to users.
pub const TAB_EMOJI: &str = "<:tab:1459045305084547123>";

/// Side length in pixels of the PNG preview generated by `/color preview`.
pub const COLOR_PREVIEW_SIZE: u32 = 256;
